server:
  port: 19999

# logging level config.
log:
  level: debug # debug, info, warn, error.

redis:
  addr: 47.99.161.195:9999
  host: 47.99.161.195
  port: 9999
  password: lel999
  db: 9

# mongodb config.
mongodb:
  uri: mongodb://root:lelMongo@42.192.51.141:27017
  username: root
  password: lelMongo
  database: lel_db_notice
  host: 42.192.51.141
  port: 27017

# 豆瓣resource config
DouBan:
  tag:
    movie: https://movie.douban.com/j/search_tags?type=movie
    tv: https://movie.douban.com/j/search_tags?type=tv
  subjectAbstractUrl: https://movie.douban.com/j/subject_abstract?subject_id=%s
  movie:
    url: https://movie.douban.com/j/search_subjects?type=movie&tag=%s&sort=%s&page_limit=%s&page_start=%s
  tv:
    url: https://movie.douban.com/j/search_subjects?type=tv&tag=%s&sort=%s&page_limit=%s&page_start=%s

# get proxy ip request url.
proxy:
  reqUrl: http://47.99.161.195:5010/get/